name: SPN-Benchmarks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core scientific and data handling
  - numpy
  - scipy
  - h5py
  - joblib
  - numba
  # Utilities
  - tqdm
  - graphviz
  - scikit-learn
  - jsonpickle
  - jsonschema
  # Excel file handling
  - xlrd
  - xlwt
  - xlutils
  # Pip-specific, if any, can be added here
  # - pip:
  #   - some-pip-package
