name: SPN-Benchmarks
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core scientific and data handling
  - numpy
  - scipy
  - h5py
  - joblib
  - numba
  # Deep learning and GNN
  - pytorch
  - torchvision
  - dgl
  - torch-scatter
  # Utilities
  - tqdm
  - graphviz
  - tensorboard
  - tensorboardx
  - scikit-learn
  - jsonpickle
  - jsonschema
  # Excel file handling
  - xlrd
  - xlwt
  - xlutils
  # Build-time
  - cython
  # Pip-specific, if any, can be added here
  # - pip:
  #   - some-pip-package
